"""
Feature Agent — orchestrator.
Wires the team together. Contains no business logic.
See team/AGENTS.md for the full team description.
"""

import os
import sys
import uuid
import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from langgraph.graph import StateGraph, END

from team.state import AgentState
from team.scanner.agent import scan_project
from team.planner.agent import planner
from team.builder.agent import build_file
from team.reviewer.agent import review_file
from team.integrator.agent import integrate
from team.skills.github import get_repo, create_branch, apply_changes, open_pr
from team.skills.supabase import insert_message


def route(state: AgentState) -> str:
    return "build_file" if state["pending_files"] else "integrate"


def create_pr(state: AgentState) -> AgentState:
    repo = get_repo()
    timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    run_id = state["run_id"]
    branch = f"feat/{state['component_name'].lower()}-{timestamp}"

    create_branch(repo, branch)
    apply_changes(repo, branch, state["final_files"], run_id=run_id)

    changed_paths = "\n".join(
        f"- `{f['path']}` ({f['action']})" for f in state["final_files"]
    )
    pr_url = open_pr(
        repo=repo,
        branch=branch,
        title=f"feat: {state['component_name']} [{run_id}]",
        body=(
            f"Generated by Feature Agent.\n\n"
            f"**Run ID:** `{run_id}`\n"
            f"**Task:** {state['task_description']}\n\n"
            f"**Changes:**\n{changed_paths}"
        ),
    )
    print(f"[orchestrator] PR opened: {pr_url}")
    return {**state, "pr_url": pr_url}


def report(state: AgentState) -> AgentState:
    insert_message(
        role="agent",
        content=f"PR created for {state['component_name']}: {state['pr_url']}",
    )
    print(f"[orchestrator] done — {state['pr_url']}")
    return state


def build_graph():
    graph = StateGraph(AgentState)

    graph.add_node("scan_project", scan_project)
    graph.add_node("planner", planner)
    graph.add_node("build_file", build_file)
    graph.add_node("review_file", review_file)
    graph.add_node("integrate", integrate)
    graph.add_node("create_pr", create_pr)
    graph.add_node("report", report)

    graph.set_entry_point("scan_project")
    graph.add_edge("scan_project", "planner")
    graph.add_conditional_edges("planner", route, {"build_file": "build_file", "integrate": "integrate"})
    graph.add_edge("build_file", "review_file")
    graph.add_conditional_edges("review_file", route, {"build_file": "build_file", "integrate": "integrate"})
    graph.add_edge("integrate", "create_pr")
    graph.add_edge("create_pr", "report")
    graph.add_edge("report", END)

    return graph.compile()


if __name__ == "__main__":
    build_graph().invoke({
        "task_description": os.environ["TASK_DESCRIPTION"],
        "component_name": os.environ["COMPONENT_NAME"],
        "target_page": os.environ.get("TARGET_PAGE", "src/app/page.tsx"),
        "project_tree": "",
        "key_files": {},
        "plan": [],
        "pending_files": [],
        "current_file": {},
        "built_files": [],
        "final_files": [],
        "pr_url": "",
        "run_id": str(uuid.uuid4())[:8],
        "deploy_status": "",
    })
